import Image from "next/image";
import { Geist, Geist_Mono } from "next/font/google";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function Home() {
  return (
    <div
      className={`${geistSans.className} ${geistMono.className} font-sans grid grid-rows-[20px_1fr_20px] items-center justify-items-center min-h-screen p-8 pb-20 gap-16 sm:p-20`}
    >
      <head>
        <title>DreamStream - Your favourite sreaming website</title>   
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />     
      </head>
      <div className="text-center-black">
        Hey there! This is a demo website for a streaming service called{" "}
        <span className="font-mono font-bold">DreamStream</span>. It is built
        using{" Next.js"} and{" Tailwind CSS"}.
      </div>
      
    </div>
  );
}
